/** Generated canonical raw header schema for *_Raw sheet ordering. */

const RAW_SCHEMA_COMMON_ = {
  "pelapor": [
    "Sumber Laporan",
    "Nama unit pelapor",
    "Provinsi",
    "Kab/Kota",
    "Nama Petugas",
    "No Whatsapp Petugas",
    "Email Petugas",
    "Tanggal terima laporan",
    "Tanggal Pelacakan"
  ],
  "pasien": [
    "Nomor EPID",
    "NIK",
    "Nama",
    "JK",
    "Tanggal Lahir",
    "Umur (auto)",
    "Kelompok Umur Epidemiologis",
    "Nama orang tua/wali",
    "No. kontak orang tua/wali",
    "Apakah sekolah/bekerja?",
    "Kelas Saat Ini",
    "Nama sekolah/tempat bekerja",
    "Tinggi Badan (cm)",
    "Berat Badan (kg)",
    "Alamat",
    "RT",
    "RW",
    "Provinsi Pasien",
    "Kab/Kota Pasien",
    "Kecamatan",
    "Kelurahan",
    "Latitude",
    "Longitude",
    "Ambil Lokasi"
  ],
  "verifikasi": [
    "Status Verifikasi EPID",
    "Tanggal Verifikasi EPID",
    "Petugas Verifikator",
        "Review Admin Terakhir",
    "Catatan Verifikasi EPID"
  ],
  "sampel": [
    "Pemeriksaan Sampel Dilakukan",
    "Rincian Hasil Sampel",
    "Jam Pengambilan Spesimen",
    "Jenis Sampel Diuji",
    "Nomor Sampel / Lab",
    "Tanggal Hasil Sampel",
    "Hasil Pemeriksaan Sampel",
    "Interpretasi Hasil Sampel"
  ],
  "status": [
    "Status Pasien/Kasus",
    "Tanggal Update Status",
    "Dasar Penetapan Status",
    "Catatan Status Pasien",
    "Riwayat Status Kasus"
  ]
};

const RAW_SCHEMA_DIAGNOSIS_FIELDS_ = {
  "MR": [
    "Kasus KLB",
    "KLB ke",
    "Nomor KLB",
    "Demam?",
    "Tanggal mulai demam",
    "Ruam Makulopapular?",
    "Tanggal mulai ruam",
    "Batuk",
    "Pilek",
    "Mata merah",
    "Arthralgia",
    "Bagian Sendi",
    "Adenopathy",
    "Lokasi Adenopathy",
    "Kehamilan",
    "Umur kehamilan",
    "Gejala lain",
    "Sebutkan gejala lain",
    "Diare",
    "Bronchopneumonia",
    "Kebutaan",
    "Otitis media",
    "Pneumonia",
    "Encephalitis",
    "Malnutrisi",
    "Ulkus mukosa mulut",
    "Lainnya komplikasi",
    "Sebutkan komplikasi lain",
    "Apakah dirawat inap?",
    "Nama Rumah Sakit",
    "Nomor Rekam Medik",
    "Tanggal Masuk Rawat Inap",
    "Status Pasien Rawat Inap",
    "Tanggal Pulang",
    "Pemberian Vitamin A",
    "Ada kasus serupa di lingkungan",
    "Jumlah kasus sekitar",
    "Riwayat perjalanan 7-21 hari",
    "Lokasi perjalanan",
    "Tanggal pergi",
    "Tanggal pulang perjalanan",
    "Riwayat kontak kasus serupa",
    "Riwayat kunjungan fasilitas kesehatan",
    "Cluster/kejadian luar biasa",
    "Apakah spesimen darah diambil",
    "Jenis Sampel Darah",
    "Tanggal ambil spesimen darah",
    "Tanggal pengiriman spesimen darah ke lab",
    "Apakah spesimen lain diambil",
    "Jenis Sampel Lain",
    "Tanggal ambil spesimen lain",
    "Tanggal pengiriman spesimen lain ke lab",
    "Status akhir kasus",
    "Tanggal meninggal",
    "Penyebab kematian"
  ],
  "DIF": [
    "Nama Kantor & Jabatan",
    "No. kontak pasien",
    "Orang tua/Wali/Saudara dekat",
    "No. Telepon Wali",
    "Alamat Lengkap Wali",
    "Desa/Kelurahan Wali",
    "Kecamatan Wali",
    "Kab/Kota Wali",
    "Provinsi Wali",
    "Pekerjaan",
    "Alamat tempat kerja",
    "Tanggal mulai sakit",
    "Keluhan Utama",
    "Demam",
    "Tanggal mulai demam",
    "Sakit tenggorokan?",
    "Tanggal sakit tenggorokan",
    "Bull neck",
    "Tanggal leher bengkak",
    "Sesak nafas?",
    "Tanggal sesak nafas",
    "Pseudomembran?",
    "Tanggal pseudomembran",
    "Lokasi pseudomembran",
    "Gejala lain DIF",
    "Status Gizi",
    "Swab diambil?",
    "Lokasi ambil swab",
    "Tanggal ambil swab",
    "No Kode Spesimen",
    "Tanggal kirim swab",
    "Rawat inap?",
    "Berobat ke RS?",
    "Tanggal berobat RS",
    "Tracheostomi",
    "Berobat ke Puskesmas?",
    "Tanggal berobat Puskesmas",
    "Berobat ke Dokter Swasta?",
    "Tanggal berobat Dokter Swasta",
    "Berobat ke Perawat/Bidan?",
    "Tanggal berobat Perawat/Bidan",
    "Tidak berobat",
    "Diagnosis suspek difteri",
    "Tanggal diagnosis suspek",
    "Antibiotik diberikan?",
    "Jenis antibiotik",
    "Tanggal antibiotik",
    "ADS diberikan?",
    "Dosis ADS (IU)",
    "Tanggal ADS",
    "Alasan tidak ADS",
    "Obat lain DIF",
    "Kondisi kasus saat ini",
    "Tanggal sembuh DIF",
    "Tanggal meninggal DIF",
    "Riwayat perjalanan 10 hari",
    "Daerah perjalanan DIF",
    "Riwayat kontak suspek/konfirmasi difteri",
    "Nama alamat kontak DIF"
  ],
  "PERT": [
    "Tanggal mulai batuk",
    "Batuk terus menerus?",
    "Batuk ≥ 2 minggu?",
    "Whoop",
    "Muntah setelah batuk",
    "Apnea",
    "Tanggal mulai apnea",
    "Gejala lain pertusis",
    "Rawat inap?",
    "Nama Rumah Sakit",
    "Nomor Rekam Medik",
    "Tanggal Masuk Rawat Inap",
    "Tanggal Keluar",
    "Kontak batuk lama",
    "Ada klaster/kejadian serupa",
    "Jumlah kasus sekitar PERT",
    "Perjalanan 1 bulan PERT",
    "Lokasi perjalanan PERT",
    "Tanggal pergi PERT",
    "Tanggal kembali PERT",
    "Spesimen pertusis diambil?",
    "Tanggal ambil spesimen pertusis",
    "Jenis spesimen pertusis",
    "Tanggal kirim spesimen pertusis",
    "Spesimen lain pertusis diambil?",
    "Jenis spesimen lain pertusis",
    "Tanggal ambil spesimen lain pertusis",
    "Tanggal kirim spesimen lain pertusis",
    "Status akhir PERT",
    "Tanggal meninggal PERT"
  ],
  "TN": [
    "Nama Ibu",
    "Anak ke-",
    "Usia ibu",
    "Pekerjaan ibu",
    "Pendidikan ibu",
    "Lama tinggal di desa",
    "Apakah bayi lahir hidup",
    "Bayi menangis saat lahir",
    "Tanda kelahiran hidup",
    "Bayi bisa menyusu dengan baik",
    "Mulut mencucu dan tidak bisa menyusu",
    "Bayi mudah kejang",
    "Tanggal mulai sakit",
    "Apakah bayi dirawat",
    "Tempat perawatan TN",
    "Tanggal mulai dirawat TN",
    "Keadaan bayi setelah dirawat",
    "Tanggal meninggal TN",
    "Umur bayi meninggal (hari)",
    "Jumlah kunjungan ANC",
    "Tempat pemeriksaan ibu hamil",
    "Pemeriksa kehamilan",
    "Pemeriksa kehamilan lainnya",
    "Tempat persalinan",
    "Tempat persalinan lainnya",
    "Usia gestasi",
    "Penolong persalinan",
    "Penolong persalinan lainnya",
    "Alat potong tali pusat",
    "Alat potong tali pusat lainnya",
    "Perawatan tali pusat",
    "Perawatan tali pusat lainnya",
    "Keadaan ibu saat ini",
    "Sumber informasi imunisasi ibu",
    "Td kehamilan ini",
    "Jumlah Td kehamilan ini",
    "Usia kehamilan Td1",
    "Tanggal Td1 kehamilan ini",
    "Usia kehamilan Td2",
    "Tanggal Td2 kehamilan ini",
    "Td kehamilan sebelumnya",
    "Tanggal Td1 kehamilan sebelumnya",
    "Tanggal Td2 kehamilan sebelumnya",
    "Td calon pengantin",
    "Tanggal Td calon pengantin",
    "Riwayat DPT-HB-HiB 1 ibu",
    "Riwayat DPT-HB-HiB 2 ibu",
    "Riwayat DPT-HB-HiB 3 ibu",
    "Riwayat DPT-HB-HiB 4 ibu",
    "Riwayat DT kelas 1 ibu",
    "Riwayat Td kelas 2 ibu",
    "Riwayat Td kelas 5 ibu",
    "Status T ibu",
    "Status imunisasi TT/Td ibu",
    "Vaksin Td saat investigasi",
    "Tanggal vaksin Td saat investigasi",
    "Cakupan DPT-HB-Hib 1",
    "Cakupan DPT-HB-Hib 2",
    "Cakupan DPT-HB-Hib 3",
    "Cakupan DT Kelas 1",
    "Cakupan Td kelas 2",
    "Cakupan Td kelas 5",
    "Cakupan TT 2+",
    "Cakupan persalinan faskes",
    "Cakupan KN1",
    "Cakupan KN2",
    "Cakupan KN3",
    "Akses desa ke faskes",
    "Faktor pelaksanaan imunisasi",
    "Faktor pertolongan persalinan",
    "Berat lahir",
    "Riwayat kasus serupa di wilayah",
    "Status akhir TN"
  ],
  "AFP": [
    "Tanggal mulai sakit/gejala awal",
    "Tgl mulai lumpuh",
    "Sifat akut",
    "Lumpuh layuh",
    "Asimetris",
    "Demam saat onset",
    "Rudapaksa AFP",
    "Pengobatan tradisional AFP",
    "Nama tempat pengobatan tradisional AFP",
    "Tanggal berkunjung pengobatan tradisional AFP",
    "Berobat ke Rumah Sakit AFP",
    "Nama Rumah Sakit",
    "Tanggal berobat AFP",
    "Diagnosis AFP",
    "Nomor Rekam Medik",
    "Tanggal meninggal AFP",
    "Tungkai kanan lumpuh",
    "Tungkai kanan kekuatan",
    "Tungkai kanan rasa raba",
    "Tungkai kiri lumpuh",
    "Tungkai kiri kekuatan",
    "Tungkai kiri rasa raba",
    "Lengan kanan lumpuh",
    "Lengan kanan kekuatan",
    "Lengan kanan rasa raba",
    "Lengan kiri lumpuh",
    "Lengan kiri kekuatan",
    "Lengan kiri rasa raba",
    "Lokasi kelumpuhan",
    "Perjalanan 35 hari AFP",
    "Lokasi perjalanan AFP",
    "Tanggal pergi AFP",
    "Kontak OPV 75 hari AFP",
    "Punya jamban sendiri",
    "Jenis jamban",
    "Jenis jamban lainnya",
    "Selalu pakai jamban",
    "Jamban aman",
    "Pembuangan diapers",
    "Pembuangan diapers lainnya",
    "Dosis OPV rutin",
    "Dosis IPV rutin",
    "Dosis Hexavalen rutin",
    "Sumber info imunisasi rutin AFP",
    "Program imunisasi tambahan AFP",
    "Dosis OPV tambahan AFP",
    "Dosis IPV tambahan AFP",
    "Sumber info imunisasi tambahan AFP",
    "Tanggal OPV terakhir AFP",
    "Tanggal IPV terakhir AFP",
    "Tanggal Hexavalen terakhir AFP",
    "Spesimen tinja 1 diambil?",
    "Tanggal tinja 1",
    "Tanggal kirim tinja 1 kab-prov",
    "Tanggal kirim tinja 1 prov-lab",
    "Spesimen tinja 2 diambil?",
    "Tanggal tinja 2",
    "Tanggal kirim tinja 2 kab-prov",
    "Tanggal kirim tinja 2 prov-lab",
    "Alasan tidak diambil spesimen AFP",
    "Kondisi spesimen baik",
    "Hasil pemeriksaan AFP",
    "Nama dokter AFP",
    "No. Telp dokter AFP",
    "Tanggal follow up 60 hari",
    "Masih ada kelumpuhan"
  ]
};

const RAW_SCHEMA_SYSTEM_FIELDS_ = [
  "DX",
  "Tanggal Input",
  "Tanggal Update",
  "Timestamp",
  "Last Updated At",
  "Diinput Oleh",
  "Role Penginput",
  "Tahap Workflow Terakhir",
  "Label Tahap Workflow Terakhir",
  "Diupdate Oleh Tahap Terakhir",
  "Role Pengupdate Tahap Terakhir",
  "Waktu Update Tahap Terakhir",
  "Workflow Current Queue",
  "Workflow Current Label",
  "Status Proses Verifikasi EPID",
  "Status Proses Pemeriksaan",
  "Status Proses Pemantauan",
  "Status Proses Perbaikan",
  "Workflow Selesai",
  "Edited At",
  "Edited By",
  "Edit Reason",
  "Edit Diff Summary",
  "Edit Inputan Perlu Review Ulang",
  "Edit Inputan Review Note"
];

const RAW_SCHEMA_PIPELINE_FIELDS_ = [
  "Kecamatan Pengampu",
  "Kelurahan Pengampu",
  "KodeFaskes Pengampu",
  "Puskesmas Pengampu",
  "Kepala Puskesmas Pengampu",
  "Email Kapus Pengampu",
  "Petugas Surveilans Pengampu",
  "Email Petugas Pengampu",
  "SpreadsheetId Pengampu",
  "SpreadsheetUrl Pengampu",
  "Telegram Chat Id Pengampu",
  "Status Routing Pengampu",
  "Status Notifikasi Pengampu",
  "Reason Notifikasi Pengampu",
  "Notified At Pengampu",
  "Notified To Pengampu",
  "Status Sinkronisasi Pengampu",
  "Reason Sinkronisasi Pengampu",
  "Synced At Pengampu",
  "Sync Target Pengampu",
  "Status Notifikasi Telegram",
  "Reason Notifikasi Telegram",
  "Telegram Notified At",
  "Telegram Target",
  "Telegram Retry Count",
  "Status Notifikasi WAHA",
  "Reason Notifikasi WAHA",
  "WAHA Notified At",
  "WAHA Target",
  "Status Notifikasi Kasus Baru WAHA",
  "Reason Notifikasi Kasus Baru WAHA",
  "Kasus Baru WAHA Notified At",
  "Kasus Baru WAHA Target",
  "Status Notifikasi Revisi WAHA",
  "Reason Notifikasi Revisi WAHA",
  "Revision WAHA Notified At",
  "Revision WAHA Target",
  "Pipeline Fingerprint",
  "Pipeline Last Run At",
  "Status Notifikasi Revisi Pengampu",
  "Reason Notifikasi Revisi Pengampu",
  "Revision Notified At Pengampu",
  "Revision Notified To Pengampu",
  "Status Notifikasi Revisi Telegram",
  "Reason Notifikasi Revisi Telegram",
  "Revision Telegram Notified At",
  "Revision Telegram Target",
  "Revision Notification Fingerprint",
  "Revision Notification Last Run At"
];

const RAW_SCHEMA_INTERNAL_FIELDS_ = [
  "ID Registrasi Kasus",
  "Status Verifikasi Sebelumnya",
  "Notifikasi Revisi Dibaca",
  "Waktu Permintaan Revisi",
  "Waktu Verifikasi Pending",
  "Review Admin Terakhir"
];


function _rawSchemaDedupe_(items) {
  var out = [];
  var seen = {};
  (items || []).forEach(function(item) {
    var key = String(item || '').trim();
    if (!key || seen[key]) return;
    seen[key] = true;
    out.push(key);
  });
  return out;
}

function getCanonicalRawHeaderOrder_(dx) {
  var code = String(dx || '').trim().toUpperCase();
  var diagnosisFields = RAW_SCHEMA_DIAGNOSIS_FIELDS_[code] || [];
  return _rawSchemaDedupe_([
    'ID Registrasi Kasus',
    'Nomor EPID',
      ]
    .concat(RAW_SCHEMA_SYSTEM_FIELDS_ || [])
    .concat((RAW_SCHEMA_COMMON_ && RAW_SCHEMA_COMMON_.pelapor) || [])
    .concat((RAW_SCHEMA_COMMON_ && RAW_SCHEMA_COMMON_.pasien) || [])
    .concat(diagnosisFields)
    .concat((RAW_SCHEMA_COMMON_ && RAW_SCHEMA_COMMON_.verifikasi) || [])
    .concat((RAW_SCHEMA_COMMON_ && RAW_SCHEMA_COMMON_.sampel) || [])
    .concat((RAW_SCHEMA_COMMON_ && RAW_SCHEMA_COMMON_.status) || [])
    .concat(RAW_SCHEMA_PIPELINE_FIELDS_ || [])
    .concat(RAW_SCHEMA_INTERNAL_FIELDS_ || []));
}
