const pptxgen = require('pptxgenjs');
const pptx = new pptxgen();
pptx.layout='LAYOUT_WIDE'; pptx.author='SIMPEL Surveilans'; pptx.subject='Sosialisasi untuk Faskes Klinik'; pptx.title='SIMPEL Surveilans — Sosialisasi Faskes Klinik'; pptx.company='Dinas Kesehatan Kota Depok';
pptx.theme={headFontFace:'Aptos Display',bodyFontFace:'Aptos',lang:'id-ID'};
const C={navy:'12304A', teal:'13A6A6', mint:'E8F6F4', gold:'F4B942', ink:'203040', gray:'607080', pale:'F5F8FA', white:'FFFFFF', red:'D95D5D'};
function base(s,title,kicker){s.background={color:C.white}; s.addShape(pptx.ShapeType.rect,{x:0,y:0,w:.18,h:7.5,fill:{color:C.teal},line:{color:C.teal}}); if(kicker)s.addText(kicker.toUpperCase(),{x:.6,y:.35,w:11.5,h:.22,fontSize:9,bold:true,color:C.teal,charSpacing:1.3}); if(title)s.addText(title,{x:.6,y:.65,w:11.6,h:.55,fontSize:25,bold:true,color:C.navy,margin:0}); s.addText('SIMPEL Surveilans  |  Klinik',{x:.6,y:7.15,w:5,h:.18,fontSize:8,color:'8293A0',margin:0});}
function bullets(s,items,x=.8,y=1.55,w=11,h=4.8,size=18){items.forEach((t,i)=>{s.addShape(pptx.ShapeType.ellipse,{x,y:y+i*.62+0.08,w:.12,h:.12,fill:{color:C.teal},line:{color:C.teal}});s.addText(t,{x:x+.28,y:y+i*.62,w,h:.38,fontSize:size,color:C.ink,breakLine:false,fit:'shrink',margin:0});});}
function card(s,x,y,w,h,title,text,color=C.mint){s.addShape(pptx.ShapeType.roundRect,{x,y,w,h,rectRadius:.08,fill:{color},line:{color}});s.addText(title,{x:x+.22,y:y+.18,w:w-.44,h:.3,fontSize:15,bold:true,color:C.navy,margin:0});s.addText(text,{x:x+.22,y:y+.62,w:w-.44,h:h-.75,fontSize:12,color:C.ink,fit:'shrink',margin:0.02});}
let s=pptx.addSlide(); s.background={color:C.navy}; s.addShape(pptx.ShapeType.arc,{x:8.8,y:-1.2,w:5,h:5,line:{color:C.teal,transparency:25,pt:8}}); s.addShape(pptx.ShapeType.arc,{x:9.6,y:3.8,w:4,h:4,line:{color:C.gold,transparency:20,pt:5}}); s.addText('SIMPEL\nSurveilans',{x:.8,y:1.55,w:6.5,h:1.6,fontSize:38,bold:true,color:C.white,margin:0,breakLine:false}); s.addText('Sosialisasi untuk Fasilitas Pelayanan Kesehatan Klinik',{x:.85,y:3.55,w:7.5,h:.5,fontSize:20,color:'D9EEF0',margin:0}); s.addText('Laporan cepat  •  Data lengkap  •  Tindak lanjut tepat',{x:.85,y:5.45,w:8,h:.3,fontSize:15,bold:true,color:C.gold,margin:0}); s.addText('Kota Depok',{x:.85,y:6.65,w:4,h:.25,fontSize:12,color:'B9CBD5',margin:0});
s=pptx.addSlide();base(s,'Tujuan Sosialisasi','01 | Arah kegiatan');bullets(s,['Memahami peran klinik dalam surveilans penyakit berpotensi KLB.','Mampu menginput laporan awal secara lengkap dan benar.','Memahami alur Nomor EPID, verifikasi, pemeriksaan, dan tindak lanjut.','Menjaga keamanan akun serta kerahasiaan data pasien.']);
s=pptx.addSlide();base(s,'Mengapa Klinik Penting?','02 | Peran klinik');card(s,.8,1.6,3.55,2.4,'Deteksi awal','Klinik sering menjadi titik pertama pasien mencari pertolongan.',C.mint);card(s,4.65,1.6,3.55,2.4,'Data terpercaya','Data klinis dan epidemiologis yang lengkap mempercepat verifikasi.',C.pale);card(s,8.5,1.6,3.55,2.4,'Respons cepat','Laporan tepat waktu membantu petugas menentukan tindak lanjut.', 'FFF5DD');s.addText('SIMPEL Surveilans melengkapi rekam medis klinik. Aplikasi ini digunakan untuk pelaporan dan surveilans program.',{x:1,y:5.1,w:10.8,h:.7,fontSize:20,bold:true,color:C.navy,align:'center',valign:'mid',margin:.1});
s=pptx.addSlide();base(s,'Alur Kerja Utama','03 | Workflow');const steps=['Login','Input kasus','Simpan laporan','Verifikasi EPID','Pemeriksaan / spesimen','Pemantauan status'];steps.forEach((t,i)=>{let x=.75+i*2.05;s.addShape(pptx.ShapeType.ellipse,{x,y:2.15,w:.7,h:.7,fill:{color:i<3?C.teal:C.navy},line:{color:i<3?C.teal:C.navy}});s.addText(String(i+1),{x,y:2.31,w:.7,h:.2,fontSize:16,bold:true,color:C.white,align:'center',margin:0});s.addText(t,{x:x-.35,y:3.1,w:1.4,h:.55,fontSize:13,bold:true,color:C.ink,align:'center',fit:'shrink',margin:0});if(i<5)s.addShape(pptx.ShapeType.line,{x:x+.75,y:2.5,w:1.25,h:0,line:{color:'A9BCC5',pt:2,beginArrowType:'none',endArrowType:'triangle'}})});s.addText('Nomor EPID ditetapkan melalui proses verifikasi. Jangan mengisi atau mengubahnya secara manual.',{x:1,y:5.25,w:10.8,h:.5,fontSize:18,bold:true,color:C.red,align:'center',margin:0});
s=pptx.addSlide();base(s,'Sebelum Input Kasus','04 | Persiapan');bullets(s,['Siapkan identitas pasien dari sumber resmi klinik.','Pastikan NIK, nama, jenis kelamin, tanggal lahir, dan alamat benar.','Siapkan tanggal laporan diterima, tanggal pelacakan, serta data petugas.','Siapkan data gejala, pemeriksaan, dan spesimen bila tersedia.','Gunakan data simulasi saat pelatihan — bukan data pasien nyata.']);
s=pptx.addSlide();base(s,'Input Kasus dengan Benar','05 | Praktik inti');card(s,.8,1.45,5.65,4.7,'Isi berdasarkan bukti','• Pilih diagnosis/formulir yang sesuai\n• Isi tanggal dengan tepat\n• Jawab sesuai anamnesis atau pemeriksaan\n• Jangan mengisi data dengan perkiraan\n• Periksa unit pelapor dan wilayah pasien',C.mint);card(s,6.75,1.45,5.65,4.7,'Sebelum klik Simpan','• Baca ringkasan validasi\n• Lengkapi field wajib\n• Klik Simpan satu kali\n• Tunggu notifikasi berhasil\n• Catat identitas kasus bila tampil',C.pale);
s=pptx.addSlide();base(s,'Verifikasi EPID dan Tindak Lanjut','06 | Tahap setelah laporan');bullets(s,['Laporan awal masuk ke antrean verifikasi admin.','Klinik dapat diminta melengkapi atau mengklarifikasi data.','Setelah terverifikasi, tahap pemeriksaan atau pemantauan tersedia sesuai hak akses.','Jika ada kesalahan, gunakan alur perbaikan — jangan membuat kasus baru.']);
s=pptx.addSlide();base(s,'Data Pemeriksaan dan Spesimen','07 | Akurasi hasil');bullets(s,['Pastikan Nomor EPID sesuai kasus.','Isi jenis spesimen, waktu pengambilan, nomor sampel, dan tanggal pengiriman sesuai dokumen.','Jangan menebak hasil pemeriksaan.','Jika hasil belum tersedia, gunakan status yang sesuai.','Simpan dokumen pendukung mengikuti SOP klinik.']);
s=pptx.addSlide();base(s,'Keamanan Data Pasien','08 | Wajib dijaga');card(s,.8,1.5,5.65,4.7,'Lakukan','• Gunakan akun resmi dan akses sesuai role\n• Simpan OTP/password dengan aman\n• Logout dari perangkat bersama\n• Laporkan akses mencurigakan\n• Gunakan data hanya untuk tugas resmi',C.mint);card(s,6.75,1.5,5.65,4.7,'Hindari','• Membagikan OTP\n• Mengirim screenshot ke grup umum\n• Mengunduh data tanpa kebutuhan\n• Membuat laporan ganda\n• Mengubah status tanpa kewenangan', 'FFF0F0');
s=pptx.addSlide();base(s,'Masalah Umum dan Solusi','09 | Dukungan operasional');const probs=[['Tidak bisa login','Cek email, OTP, koneksi, dan status akun.'],['Nomor EPID belum ada','Normal pada laporan awal; tunggu verifikasi.'],['Kasus sudah pernah dilaporkan','Cari kasus yang ada; jangan buat duplikat.'],['Simpan tidak merespons','Cek validasi dan jangan klik berulang.'],['Menu tidak tersedia','Periksa role dan tahap workflow; hubungi admin.']];probs.forEach((p,i)=>{let y=1.35+i*.95;s.addShape(pptx.ShapeType.roundRect,{x:.85,y,w:3.2,h:.62,rectRadius:.05,fill:{color:C.mint},line:{color:C.mint}});s.addText(p[0],{x:1.05,y:y+.18,w:2.8,h:.2,fontSize:13,bold:true,color:C.navy,margin:0});s.addText(p[1],{x:4.35,y:y+.18,w:7.4,h:.25,fontSize:14,color:C.ink,margin:0});});
s=pptx.addSlide();base(s,'Simulasi Praktik','10 | Latihan peserta');bullets(s,['Gunakan satu skenario dan data pasien simulasi.','Pilih formulir diagnosis yang sesuai.','Isi identitas, sumber laporan, gejala, dan tanggal penting.','Simpan satu kali lalu temukan laporan pada daftar/antrean.','Jelaskan perbedaan laporan awal dan kasus terverifikasi.']);
s=pptx.addSlide();base(s,'Checklist Klinik','11 | Siap digunakan');const checks=['Akun klinik aktif','Petugas memahami kewenangan','Data pasien berasal dari sumber resmi','Diagnosis dan unit pelapor benar','Tanggal dan wilayah sudah diperiksa','Notifikasi simpan berhasil','Tindak lanjut dipantau','Kerahasiaan data dijaga'];checks.forEach((t,i)=>{let col=i%2,row=Math.floor(i/2);s.addShape(pptx.ShapeType.roundRect,{x:.9+col*5.8,y:1.4+row*1.15,w:5.2,h:.72,rectRadius:.05,fill:{color:row%2?C.pale:C.mint},line:{color:row%2?C.pale:C.mint}});s.addText('✓  '+t,{x:1.15+col*5.8,y:1.63+row*1.15,w:4.7,h:.2,fontSize:15,bold:true,color:C.navy,margin:0});});
s=pptx.addSlide();s.background={color:C.navy};s.addText('Terima kasih',{x:.8,y:1.8,w:6,h:.7,fontSize:36,bold:true,color:C.white,margin:0});s.addText('Bersama memperkuat surveilans kesehatan\ndi Kota Depok.',{x:.85,y:3,w:7,h:.8,fontSize:23,color:'D9EEF0',margin:0});s.addText('Laporan cepat  •  Data lengkap  •  Tindak lanjut tepat',{x:.85,y:5.35,w:8,h:.3,fontSize:16,bold:true,color:C.gold,margin:0});s.addText('Kontak bantuan: Admin SIMPEL Surveilans / Petugas Surveilans Dinas Kesehatan',{x:.85,y:6.55,w:10,h:.25,fontSize:11,color:'B9CBD5',margin:0});
pptx.writeFile({fileName:'/root/.openclaw/workspace/projects/gas-pe-pd3i/docs/Materi_Sosialisasi_SIMPEL_Surveilans_Faskes_Klinik.pptx'});
